hyper:
    batch_size: 64
    gpu_ids: 0
    logs_dir: ../CS++_concat/diff_crossattn
    results_dir: ../CS++_concat/diff_crossattn
    name: ./
    isTrain: True
    device: 'cuda'
    distributed: 0
    lr_init: 1e-4
    lr_step: [35000, 70000, 120000]
    lr_evo: [5e-5, 1e-5, 5e-6]
dataset:
    res: 64
    trunc_thres: 0.2
    ratio: 1

layout_branch:
    model: diffusion_scene_layout_ddpm
    angle_dim: 2
    denoiser: unet1d
    relation_condition: true
    denoiser_kwargs:
        dims: 1 # 1D
        in_channels: 8 # size(3)+loc(3)+sincos(2)
        out_channels: 8 # same
        model_channels: 512
        channel_mult: [ 1,1,1,1]
        num_res_blocks: 2
        attention_resolutions: [ 4, 2 ]
        num_heads: 8
        # cond_model params
        use_spatial_transformer: false
        transformer_depth: 1
        conditioning_key: 'concat'
        concat_dim: 1280
        crossattn_dim: 1280
        use_checkpoint: true
        enable_t_emb: true

    diffusion_kwargs:
      schedule_type: 'linear'
      beta_start: 0.0001
      beta_end: 0.02
      time_num: 1000
      loss_type: 'diffuscene'
      model_mean_type: 'eps'
      model_var_type: 'fixedsmall'
      loss_separate: true
      loss_iou: false
      iou_type: obb
      train_stats_file: null

shape_branch:
    model: sdfusion-txt2shape_concat_mp
    sampling: greedy
    ckpt: null
    df_cfg: ../config/sdfusion-txt2shape_concat_mp.yaml
    ddim_steps: 100
    ddim_eta: 0.0
    uc_scale: 3.0
    vq_model: vqvae
    vq_cfg: ../config/vqvae_snet.yaml
    vq_dset: None
    vq_cat: None
    vq_ckpt: ./checkpoint/vqvae_threedfront_best.pth
misc:
    debug: 0
    seed: 111
    backend: gloo
    local_rank: 0

training:
    lr: 1e-5
    lr_policy: lambda
    lr_decay_iters: 50
    lambda_L1: 10.0
